### ISSUE TITLE
【重要】请更换有道翻译Key

### ISSUE THREAD

**Issue by unbug** [voldikss/vim-codelf#2]
由于有道翻译有诸多限制（请求数量，域名等）。
请自己申请一个有道翻译的Key，以免影响用户正常实用 CODELF。
其他可替换的翻译API有：Bing 翻译，Baidu 翻译。

https://github.com/voldikss/vim-codelf/blob/a0388029056e6106f6194f97779353688eb9d2e0/script/codelf.py#L40

**Comment by voldikss** [comment]
好的，我马上修改

**Comment by voldikss** [comment]
已经去掉了，不再需要 key

**Comment by unbug** [comment]
不需要 Key 也能用吗？有趣

**Comment by voldikss** [comment]
有一个古老的 API 😂

Unbug Lee <notifications@github.com> 于 2019年12月31日周二 下午1:33写道：
